# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Network timeout configuration
org.gradle.internal.http.socketTimeout=120000
org.gradle.internal.http.connectionTimeout=120000

# Gradle parallelization
org.gradle.parallel=true
org.gradle.workers.max=4

# Fabric Properties
minecraft_version=1.21
yarn_mappings=1.21+build.9
loader_version=0.16.9

# Mod Properties
mod_version = 1.0-SNAPSHOT
maven_group = dev.lvstrng
archives_base_name = virgins

# Dependencies
fabric_version=0.102.0+1.21
